### ISSUE TITLE
Annict DB

### ISSUE THREAD

**Issue by shimbaco** [annict/annict#184]
利用者から作品情報など編集した「編集リクエスト」をもらい、「編集者」がその内容を公開することができる機能。

## TODO

* [x] 見た目を整える
* [x] テストを書きつつ動作確認

## デプロイのフロー

* [x] `git push heroku master`
* [x] `heroku run rake db:migrate`
* [x] `heroku run rake counter_cache:refresh_items_count_on_works`
* [x] `heroku run rake tmp:remove_hash_from_twitter_hashtag`
* [x] `heroku run rake tmp:move_next_episode_id_to_prev_episode_id`
