### ISSUE TITLE
リリース日 `released_at` を使用しないようにする

### ISSUE THREAD

**Issue by shimbaco** [annict/annict#238]
正確な日付を表示しても意味が無い気がしたので、リリース日を表示している箇所 (今は作品詳細ページくらい?) を「リリース時期 (放送時期)」に置き換え、Annict DBの入力欄も消します。

#### TODO

* [x] 「放送時期」を「リリース時期」に名称変更
* [x] 「リリース日 (大体)」を「リリース時期 (大体)」に名称変更
* [x] 「リリース日」が表示されている箇所を「リリース時期」に置き換える
* [x] 「リリース日」でソートしている部分を `works.id` の降順でソートするように置き換える
* [x] Annict DBの「リリース日」を入力する欄を消す
  * データベースのカラムは一応残しておく
