### ISSUE TITLE
Annict DB: 放送時期の選択肢周りの修正

### ISSUE THREAD

**Issue by shimbaco** [annict/annict#239]
#### TODO

* [x] `seasons` テーブルに `sort_number` を追加する
* [x] `seasons` テーブルに1917年冬季から1999年秋季までのデータを追加するrakeタスクを用意する
  * [日本の最初のアニメは1917年に公開されたらしい](https://ja.wikipedia.org/wiki/%E3%82%A2%E3%83%8B%E3%83%A1%E3%81%AE%E6%AD%B4%E5%8F%B2#.E6.97.A5.E6.9C.AC.E3.82.A2.E3.83.8B.E3.83.A1.E3.81.AE.E5.A4.9C.E6.98.8E.E3.81.91)
* [x] `seasons` テーブルの `sort_number` に良い感じに数値を入れるrakeタスクを用意する
  * 1917年冬季が1、1917年春季が2、…という感じで数値をインクリメントしながら入れる
* [x] Annict DBの「リリース時期」の選択肢を `sort_number.desc` な並び順で表示する
